---
version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  daphne:
    build: .
    command: bash -c "daphne -b 0.0.0.0 -p 8000 behavior.asgi:channel_layer"
    working_dir: '/opt/channels_redis_debug'
    ports:
      - "8000:8000"
    environment:
      - "REDIS_HOST=redis"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./:/opt/channels_redis_debug"
  nginx:
    build: ./nginx
    ports:
      - "8049:81"
    depends_on:
      - daphne
    volumes:
      - "./:/opt/channels_redis_debug"
